spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
        dialect.storage_engine: innodb
        format_sql: true
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem://localhost/~/acquire;MODE=MYSQL # MODE=MYSQL 없으면 h2가 mysql 모드로 실행이 안됨
      username: sa
      password:
      driver-class-name: org.h2.Driver
logging:
  level:
    org:
      hibernate:
        type: trace