spring:
  profiles:
    include:
      - rds
    active: local
  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
        dialect.storage_engine: innodb
        format_sql: true
    hibernate:
      ddl-auto: update
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem://localhost/~/acquire;MODE=MYSQL # MODE=MYSQL 없으면 h2가 mysql 모드로 실행이 안됨
      username: sa
      password:
      driver-class-name: org.h2.Driver
logging:
  level:
    org:
      hibernate:
        type: trace
    com:
      querydsl:
        sql: DEBUG