spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL57Dialect
      hibernate.dialect.storage_engine: innodb
      hibernate.hbm2ddl.import_files_sql_extractor: org.hibernate.tool.hbm2ddl.MultipleLinesSqlCommandExtractor
      hibernate.default_batch_fetch_size: ${chunkSize:1000}
      hibernate.query.in_clause_parameter_padding: true

    open-in-view: false
  datasource:
    hikari:
      auto-commit: false

---
spring:
  profiles: local
  h2:
    console.settings.trace: false
    console:
      enabled: true
  datasource:
    hikari:
      jdbc-url: jdbc:mysql:aurora://jojoldu.cluster-cvqgfwbdqpys.ap-northeast-2.rds.amazonaws.com:3306/jojoldu
  #    jdbc-url: jdbc:mysql:aurora://jojoldu.cluster-cvqgfwbdqpys.ap-northeast-2.rds.amazonaws.com:3306/jojoldu?connectTimeout=1000&socketTimeout=600000
  #    username: sa
  #    password:
      driver-class-name: org.mariadb.jdbc.Driver
      data-source-properties:
        connect-timeout: 10000
        socket-timeout: 60000
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

