spring:
  jpa:
    hibernate:
      ddl-auto: update
  profiles:
    active: local

cloud:
  aws:
    s3:
      bucket: jojoldu
    region:
      static: ap-northeast-2
    stack:
      auto: false
    credentials:
      instanceProfile: true

